#
# Autogenerated by Thrift Compiler (0.22.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec
from uuid import UUID

import sys

from thrift.transport import TTransport
all_structs = []


class TubeHatColor(object):
    Red = 0
    Blue = 1
    Black = 2
    Green = 3
    Purple = 4
    Gray = 5
    Orange = 6
    Yellow = 7
    White = 8
    Unknown = 9

    _VALUES_TO_NAMES = {
        0: "Red",
        1: "Blue",
        2: "Black",
        3: "Green",
        4: "Purple",
        5: "Gray",
        6: "Orange",
        7: "Yellow",
        8: "White",
        9: "Unknown",
    }

    _NAMES_TO_VALUES = {
        "Red": 0,
        "Blue": 1,
        "Black": 2,
        "Green": 3,
        "Purple": 4,
        "Gray": 5,
        "Orange": 6,
        "Yellow": 7,
        "White": 8,
        "Unknown": 9,
    }


class TubeType(object):
    HitachiMicro = 0
    Unknown = 1
    QualityControl = 3
    HitachiStandard = 2
    BloodCollection = 4
    Blank = 5

    _VALUES_TO_NAMES = {
        0: "HitachiMicro",
        1: "Unknown",
        3: "QualityControl",
        2: "HitachiStandard",
        4: "BloodCollection",
        5: "Blank",
    }

    _NAMES_TO_VALUES = {
        "HitachiMicro": 0,
        "Unknown": 1,
        "QualityControl": 3,
        "HitachiStandard": 2,
        "BloodCollection": 4,
        "Blank": 5,
    }


class TaskState(object):
    NoneState = 0
    Issued = 1
    Identifying = 2
    Finished = 3

    _VALUES_TO_NAMES = {
        0: "NoneState",
        1: "Issued",
        2: "Identifying",
        3: "Finished",
    }

    _NAMES_TO_VALUES = {
        "NoneState": 0,
        "Issued": 1,
        "Identifying": 2,
        "Finished": 3,
    }


class TaskResult(object):
    Success = 0
    CameraFault = 1
    ScripperFault = 2
    UnknownFault = 3

    _VALUES_TO_NAMES = {
        0: "Success",
        1: "CameraFault",
        2: "ScripperFault",
        3: "UnknownFault",
    }

    _NAMES_TO_VALUES = {
        "Success": 0,
        "CameraFault": 1,
        "ScripperFault": 2,
        "UnknownFault": 3,
    }


class RunningState(object):
    Ready = 0
    Reseting = 1
    Stop = 2
    Fault = 3

    _VALUES_TO_NAMES = {
        0: "Ready",
        1: "Reseting",
        2: "Stop",
        3: "Fault",
    }

    _NAMES_TO_VALUES = {
        "Ready": 0,
        "Reseting": 1,
        "Stop": 2,
        "Fault": 3,
    }


class TubeHatHSV(object):
    """
    Attributes:
     - H
     - S
     - V

    """
    thrift_spec = None


    def __init__(self, H = None, S = None, V = None,):
        self.H = H
        self.S = S
        self.V = V

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I32:
                    self.H = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I32:
                    self.S = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.I32:
                    self.V = iprot.readI32()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('TubeHatHSV')
        if self.H is not None:
            oprot.writeFieldBegin('H', TType.I32, 1)
            oprot.writeI32(self.H)
            oprot.writeFieldEnd()
        if self.S is not None:
            oprot.writeFieldBegin('S', TType.I32, 2)
            oprot.writeI32(self.S)
            oprot.writeFieldEnd()
        if self.V is not None:
            oprot.writeFieldBegin('V', TType.I32, 3)
            oprot.writeI32(self.V)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class TubeHatInfo(object):
    """
    Attributes:
     - hasHat
     - color
     - hsv

    """
    thrift_spec = None


    def __init__(self, hasHat = None, color = None, hsv = None,):
        self.hasHat = hasHat
        self.color = color
        self.hsv = hsv

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.BOOL:
                    self.hasHat = iprot.readBool()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I32:
                    self.color = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.STRUCT:
                    self.hsv = TubeHatHSV()
                    self.hsv.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('TubeHatInfo')
        if self.hasHat is not None:
            oprot.writeFieldBegin('hasHat', TType.BOOL, 1)
            oprot.writeBool(self.hasHat)
            oprot.writeFieldEnd()
        if self.color is not None:
            oprot.writeFieldBegin('color', TType.I32, 2)
            oprot.writeI32(self.color)
            oprot.writeFieldEnd()
        if self.hsv is not None:
            oprot.writeFieldBegin('hsv', TType.STRUCT, 3)
            self.hsv.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class TubeSpec(object):
    """
    Attributes:
     - width
     - height
     - top

    """
    thrift_spec = None


    def __init__(self, width = None, height = None, top = None,):
        self.width = width
        self.height = height
        self.top = top

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I32:
                    self.width = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I32:
                    self.height = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.I32:
                    self.top = iprot.readI32()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('TubeSpec')
        if self.width is not None:
            oprot.writeFieldBegin('width', TType.I32, 1)
            oprot.writeI32(self.width)
            oprot.writeFieldEnd()
        if self.height is not None:
            oprot.writeFieldBegin('height', TType.I32, 2)
            oprot.writeI32(self.height)
            oprot.writeFieldEnd()
        if self.top is not None:
            oprot.writeFieldBegin('top', TType.I32, 3)
            oprot.writeI32(self.top)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class TubeInfo(object):
    """
    Attributes:
     - hatInfo
     - type
     - spec

    """
    thrift_spec = None


    def __init__(self, hatInfo = None, type = None, spec = None,):
        self.hatInfo = hatInfo
        self.type = type
        self.spec = spec

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.hatInfo = TubeHatInfo()
                    self.hatInfo.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I32:
                    self.type = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.STRUCT:
                    self.spec = TubeSpec()
                    self.spec.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('TubeInfo')
        if self.hatInfo is not None:
            oprot.writeFieldBegin('hatInfo', TType.STRUCT, 1)
            self.hatInfo.write(oprot)
            oprot.writeFieldEnd()
        if self.type is not None:
            oprot.writeFieldBegin('type', TType.I32, 2)
            oprot.writeI32(self.type)
            oprot.writeFieldEnd()
        if self.spec is not None:
            oprot.writeFieldBegin('spec', TType.STRUCT, 3)
            self.spec.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class ImageInfo(object):
    """
    Attributes:
     - width
     - height
     - data

    """
    thrift_spec = None


    def __init__(self, width = None, height = None, data = None,):
        self.width = width
        self.height = height
        self.data = data

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I32:
                    self.width = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I32:
                    self.height = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.STRING:
                    self.data = iprot.readBinary()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('ImageInfo')
        if self.width is not None:
            oprot.writeFieldBegin('width', TType.I32, 1)
            oprot.writeI32(self.width)
            oprot.writeFieldEnd()
        if self.height is not None:
            oprot.writeFieldBegin('height', TType.I32, 2)
            oprot.writeI32(self.height)
            oprot.writeFieldEnd()
        if self.data is not None:
            oprot.writeFieldBegin('data', TType.STRING, 3)
            oprot.writeBinary(self.data)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class TubeRecgInfo(object):
    """
    Attributes:
     - barcode
     - tube
     - image

    """
    thrift_spec = None


    def __init__(self, barcode = None, tube = None, image = None,):
        self.barcode = barcode
        self.tube = tube
        self.image = image

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRING:
                    self.barcode = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.STRUCT:
                    self.tube = TubeInfo()
                    self.tube.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.STRUCT:
                    self.image = ImageInfo()
                    self.image.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('TubeRecgInfo')
        if self.barcode is not None:
            oprot.writeFieldBegin('barcode', TType.STRING, 1)
            oprot.writeString(self.barcode.encode('utf-8') if sys.version_info[0] == 2 else self.barcode)
            oprot.writeFieldEnd()
        if self.tube is not None:
            oprot.writeFieldBegin('tube', TType.STRUCT, 2)
            self.tube.write(oprot)
            oprot.writeFieldEnd()
        if self.image is not None:
            oprot.writeFieldBegin('image', TType.STRUCT, 3)
            self.image.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class TaskInfo(object):
    """
    Attributes:
     - taskId
     - gripperId
     - state
     - result
     - info

    """
    thrift_spec = None


    def __init__(self, taskId = None, gripperId = None, state = None, result = None, info = None,):
        self.taskId = taskId
        self.gripperId = gripperId
        self.state = state
        self.result = result
        self.info = info

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRING:
                    self.taskId = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I32:
                    self.gripperId = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.I32:
                    self.state = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.I32:
                    self.result = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 5:
                if ftype == TType.STRUCT:
                    self.info = TubeRecgInfo()
                    self.info.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('TaskInfo')
        if self.taskId is not None:
            oprot.writeFieldBegin('taskId', TType.STRING, 1)
            oprot.writeString(self.taskId.encode('utf-8') if sys.version_info[0] == 2 else self.taskId)
            oprot.writeFieldEnd()
        if self.gripperId is not None:
            oprot.writeFieldBegin('gripperId', TType.I32, 2)
            oprot.writeI32(self.gripperId)
            oprot.writeFieldEnd()
        if self.state is not None:
            oprot.writeFieldBegin('state', TType.I32, 3)
            oprot.writeI32(self.state)
            oprot.writeFieldEnd()
        if self.result is not None:
            oprot.writeFieldBegin('result', TType.I32, 4)
            oprot.writeI32(self.result)
            oprot.writeFieldEnd()
        if self.info is not None:
            oprot.writeFieldBegin('info', TType.STRUCT, 5)
            self.info.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class DeviceInfo(object):
    """
    Attributes:
     - runningState

    """
    thrift_spec = None


    def __init__(self, runningState = None,):
        self.runningState = runningState

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I32:
                    self.runningState = iprot.readI32()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('DeviceInfo')
        if self.runningState is not None:
            oprot.writeFieldBegin('runningState', TType.I32, 1)
            oprot.writeI32(self.runningState)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(TubeHatHSV)
TubeHatHSV.thrift_spec = (
    None,  # 0
    (1, TType.I32, 'H', None, None, ),  # 1
    (2, TType.I32, 'S', None, None, ),  # 2
    (3, TType.I32, 'V', None, None, ),  # 3
)
all_structs.append(TubeHatInfo)
TubeHatInfo.thrift_spec = (
    None,  # 0
    (1, TType.BOOL, 'hasHat', None, None, ),  # 1
    (2, TType.I32, 'color', None, None, ),  # 2
    (3, TType.STRUCT, 'hsv', [TubeHatHSV, None], None, ),  # 3
)
all_structs.append(TubeSpec)
TubeSpec.thrift_spec = (
    None,  # 0
    (1, TType.I32, 'width', None, None, ),  # 1
    (2, TType.I32, 'height', None, None, ),  # 2
    (3, TType.I32, 'top', None, None, ),  # 3
)
all_structs.append(TubeInfo)
TubeInfo.thrift_spec = (
    None,  # 0
    (1, TType.STRUCT, 'hatInfo', [TubeHatInfo, None], None, ),  # 1
    (2, TType.I32, 'type', None, None, ),  # 2
    (3, TType.STRUCT, 'spec', [TubeSpec, None], None, ),  # 3
)
all_structs.append(ImageInfo)
ImageInfo.thrift_spec = (
    None,  # 0
    (1, TType.I32, 'width', None, None, ),  # 1
    (2, TType.I32, 'height', None, None, ),  # 2
    (3, TType.STRING, 'data', 'BINARY', None, ),  # 3
)
all_structs.append(TubeRecgInfo)
TubeRecgInfo.thrift_spec = (
    None,  # 0
    (1, TType.STRING, 'barcode', 'UTF8', None, ),  # 1
    (2, TType.STRUCT, 'tube', [TubeInfo, None], None, ),  # 2
    (3, TType.STRUCT, 'image', [ImageInfo, None], None, ),  # 3
)
all_structs.append(TaskInfo)
TaskInfo.thrift_spec = (
    None,  # 0
    (1, TType.STRING, 'taskId', 'UTF8', None, ),  # 1
    (2, TType.I32, 'gripperId', None, None, ),  # 2
    (3, TType.I32, 'state', None, None, ),  # 3
    (4, TType.I32, 'result', None, None, ),  # 4
    (5, TType.STRUCT, 'info', [TubeRecgInfo, None], None, ),  # 5
)
all_structs.append(DeviceInfo)
DeviceInfo.thrift_spec = (
    None,  # 0
    (1, TType.I32, 'runningState', None, None, ),  # 1
)
fix_spec(all_structs)
del all_structs
