# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './../src/ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1400, 827)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(119, 118, 123);\n"
"border-color: rgb(119, 118, 123);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topWidget = QtWidgets.QWidget(self.centralwidget)
        self.topWidget.setObjectName("topWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.topWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lab_current_shceme = QtWidgets.QLabel(self.topWidget)
        self.lab_current_shceme.setObjectName("lab_current_shceme")
        self.horizontalLayout.addWidget(self.lab_current_shceme)
        self.comboBox_scheme = QtWidgets.QComboBox(self.topWidget)
        self.comboBox_scheme.setMinimumSize(QtCore.QSize(200, 45))
        self.comboBox_scheme.setObjectName("comboBox_scheme")
        self.horizontalLayout.addWidget(self.comboBox_scheme)
        self.btn_load_shceme = QtWidgets.QPushButton(self.topWidget)
        self.btn_load_shceme.setMinimumSize(QtCore.QSize(100, 45))
        self.btn_load_shceme.setObjectName("btn_load_shceme")
        self.horizontalLayout.addWidget(self.btn_load_shceme)
        self.btn_edit_shceme = QtWidgets.QPushButton(self.topWidget)
        self.btn_edit_shceme.setMinimumSize(QtCore.QSize(100, 45))
        self.btn_edit_shceme.setObjectName("btn_edit_shceme")
        self.horizontalLayout.addWidget(self.btn_edit_shceme)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lab_current_device = QtWidgets.QLabel(self.topWidget)
        self.lab_current_device.setObjectName("lab_current_device")
        self.horizontalLayout.addWidget(self.lab_current_device)
        self.btn_switch_device = QtWidgets.QPushButton(self.topWidget)
        self.btn_switch_device.setMinimumSize(QtCore.QSize(100, 45))
        self.btn_switch_device.setObjectName("btn_switch_device")
        self.horizontalLayout.addWidget(self.btn_switch_device)
        self.verticalLayout.addWidget(self.topWidget)
        self.contentWidget = QtWidgets.QWidget(self.centralwidget)
        self.contentWidget.setObjectName("contentWidget")
        self.contentHLayout = QtWidgets.QHBoxLayout(self.contentWidget)
        self.contentHLayout.setContentsMargins(9, 9, 9, 9)
        self.contentHLayout.setSpacing(0)
        self.contentHLayout.setObjectName("contentHLayout")
        self.videoWidget = QtWidgets.QWidget(self.contentWidget)
        self.videoWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.videoWidget.setObjectName("videoWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.videoWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lab_display = QtWidgets.QLabel(self.videoWidget)
        self.lab_display.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.lab_display.setText("")
        self.lab_display.setObjectName("lab_display")
        self.horizontalLayout_3.addWidget(self.lab_display)
        self.contentHLayout.addWidget(self.videoWidget)
        self.contentHLayout.setStretch(0, 1)
        self.verticalLayout.addWidget(self.contentWidget)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 10)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lab_current_shceme.setText(_translate("MainWindow", "当前方案：XXXXXXXXXXX"))
        self.btn_load_shceme.setText(_translate("MainWindow", "加载"))
        self.btn_edit_shceme.setText(_translate("MainWindow", "编辑"))
        self.lab_current_device.setText(_translate("MainWindow", "当前设备：XXXXXXXXXXX"))
        self.btn_switch_device.setText(_translate("MainWindow", "切换设备"))
