#
# Autogenerated by Thrift Compiler (0.22.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec
from uuid import UUID

import sys

from thrift.transport import TTransport
all_structs = []


class TubeHatColor(object):
    Red = 0
    Blue = 1
    Black = 2
    Green = 3
    Purple = 4
    Gray = 5
    Orange = 6
    Yellow = 7
    White = 8
    Unknown = 9

    _VALUES_TO_NAMES = {
        0: "Red",
        1: "Blue",
        2: "Black",
        3: "Green",
        4: "Purple",
        5: "Gray",
        6: "Orange",
        7: "Yellow",
        8: "White",
        9: "Unknown",
    }

    _NAMES_TO_VALUES = {
        "Red": 0,
        "Blue": 1,
        "Black": 2,
        "Green": 3,
        "Purple": 4,
        "Gray": 5,
        "Orange": 6,
        "Yellow": 7,
        "White": 8,
        "Unknown": 9,
    }


class TubeType(object):
    HitachiMicro = 0
    Unknown = 1
    QualityControl = 3
    HitachiStandard = 2
    BloodCollection = 4
    Blank = 5

    _VALUES_TO_NAMES = {
        0: "HitachiMicro",
        1: "Unknown",
        3: "QualityControl",
        2: "HitachiStandard",
        4: "BloodCollection",
        5: "Blank",
    }

    _NAMES_TO_VALUES = {
        "HitachiMicro": 0,
        "Unknown": 1,
        "QualityControl": 3,
        "HitachiStandard": 2,
        "BloodCollection": 4,
        "Blank": 5,
    }


class TaskState(object):
    NoneState = 0
    Issued = 1
    Identifying = 2
    Finished = 3

    _VALUES_TO_NAMES = {
        0: "NoneState",
        1: "Issued",
        2: "Identifying",
        3: "Finished",
    }

    _NAMES_TO_VALUES = {
        "NoneState": 0,
        "Issued": 1,
        "Identifying": 2,
        "Finished": 3,
    }


class TaskResult(object):
    Success = 0
    CameraFault = 1
    ScripperFault = 2
    UnknownFault = 3

    _VALUES_TO_NAMES = {
        0: "Success",
        1: "CameraFault",
        2: "ScripperFault",
        3: "UnknownFault",
    }

    _NAMES_TO_VALUES = {
        "Success": 0,
        "CameraFault": 1,
        "ScripperFault": 2,
        "UnknownFault": 3,
    }


class RunningState(object):
    Ready = 0
    Reseting = 1
    Stop = 2
    Fault = 3

    _VALUES_TO_NAMES = {
        0: "Ready",
        1: "Reseting",
        2: "Stop",
        3: "Fault",
    }

    _NAMES_TO_VALUES = {
        "Ready": 0,
        "Reseting": 1,
        "Stop": 2,
        "Fault": 3,
    }


class TubeHatHSV(object):
    """
    Attributes:
     - H
     - S
     - V

    """
    thrift_spec = None


    def __init__(self, H = None, S = None, V = None,):
        self.H = H
        self.S = S
        self.V = V

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I32:
                    self.H = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I32:
                    self.S = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.I32:
                    self.V = iprot.readI32()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('TubeHatHSV')
        if self.H is not None:
            oprot.writeFieldBegin('H', TType.I32, 1)
            oprot.writeI32(self.H)
            oprot.writeFieldEnd()
        if self.S is not None:
            oprot.writeFieldBegin('S', TType.I32, 2)
            oprot.writeI32(self.S)
            oprot.writeFieldEnd()
        if self.V is not None:
            oprot.writeFieldBegin('V', TType.I32, 3)
            oprot.writeI32(self.V)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class TubeHatInfo(object):
    """
    Attributes:
     - hasHat
     - color
     - hsv

    """
    thrift_spec = None


    def __init__(self, hasHat = None, color = None, hsv = None,):
        self.hasHat = hasHat
        self.color = color
        self.hsv = hsv

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.BOOL:
                    self.hasHat = iprot.readBool()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I32:
                    self.color = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.STRUCT:
                    self.hsv = TubeHatHSV()
                    self.hsv.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('TubeHatInfo')
        if self.hasHat is not None:
            oprot.writeFieldBegin('hasHat', TType.BOOL, 1)
            oprot.writeBool(self.hasHat)
            oprot.writeFieldEnd()
        if self.color is not None:
            oprot.writeFieldBegin('color', TType.I32, 2)
            oprot.writeI32(self.color)
            oprot.writeFieldEnd()
        if self.hsv is not None:
            oprot.writeFieldBegin('hsv', TType.STRUCT, 3)
            self.hsv.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class TubeSpec(object):
    """
    Attributes:
     - width
     - height
     - top

    """
    thrift_spec = None


    def __init__(self, width = None, height = None, top = None,):
        self.width = width
        self.height = height
        self.top = top

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I32:
                    self.width = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I32:
                    self.height = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.I32:
                    self.top = iprot.readI32()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('TubeSpec')
        if self.width is not None:
            oprot.writeFieldBegin('width', TType.I32, 1)
            oprot.writeI32(self.width)
            oprot.writeFieldEnd()
        if self.height is not None:
            oprot.writeFieldBegin('height', TType.I32, 2)
            oprot.writeI32(self.height)
            oprot.writeFieldEnd()
        if self.top is not None:
            oprot.writeFieldBegin('top', TType.I32, 3)
            oprot.writeI32(self.top)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class TubeInfo(object):
    """
    Attributes:
     - hatInfo
     - type
     - spec

    """
    thrift_spec = None


    def __init__(self, hatInfo = None, type = None, spec = None,):
        self.hatInfo = hatInfo
        self.type = type
        self.spec = spec

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.hatInfo = TubeHatInfo()
                    self.hatInfo.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I32:
                    self.type = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.STRUCT:
                    self.spec = TubeSpec()
                    self.spec.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('TubeInfo')
        if self.hatInfo is not None:
            oprot.writeFieldBegin('hatInfo', TType.STRUCT, 1)
            self.hatInfo.write(oprot)
            oprot.writeFieldEnd()
        if self.type is not None:
            oprot.writeFieldBegin('type', TType.I32, 2)
            oprot.writeI32(self.type)
            oprot.writeFieldEnd()
        if self.spec is not None:
            oprot.writeFieldBegin('spec', TType.STRUCT, 3)
            self.spec.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class SerumIndex(object):
    """
    Attributes:
     - hemolysisLevel
     - icterusLevel
     - lipemiaLevel

    """
    thrift_spec = None


    def __init__(self, hemolysisLevel = None, icterusLevel = None, lipemiaLevel = None,):
        self.hemolysisLevel = hemolysisLevel
        self.icterusLevel = icterusLevel
        self.lipemiaLevel = lipemiaLevel

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I32:
                    self.hemolysisLevel = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I32:
                    self.icterusLevel = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.I32:
                    self.lipemiaLevel = iprot.readI32()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('SerumIndex')
        if self.hemolysisLevel is not None:
            oprot.writeFieldBegin('hemolysisLevel', TType.I32, 1)
            oprot.writeI32(self.hemolysisLevel)
            oprot.writeFieldEnd()
        if self.icterusLevel is not None:
            oprot.writeFieldBegin('icterusLevel', TType.I32, 2)
            oprot.writeI32(self.icterusLevel)
            oprot.writeFieldEnd()
        if self.lipemiaLevel is not None:
            oprot.writeFieldBegin('lipemiaLevel', TType.I32, 3)
            oprot.writeI32(self.lipemiaLevel)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class SampleHeight(object):
    """
    Attributes:
     - serumHeight
     - gelHeight
     - cellsHeight
     - allSampleHeight

    """
    thrift_spec = None


    def __init__(self, serumHeight = None, gelHeight = None, cellsHeight = None, allSampleHeight = None,):
        self.serumHeight = serumHeight
        self.gelHeight = gelHeight
        self.cellsHeight = cellsHeight
        self.allSampleHeight = allSampleHeight

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.DOUBLE:
                    self.serumHeight = iprot.readDouble()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.DOUBLE:
                    self.gelHeight = iprot.readDouble()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.DOUBLE:
                    self.cellsHeight = iprot.readDouble()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.DOUBLE:
                    self.allSampleHeight = iprot.readDouble()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('SampleHeight')
        if self.serumHeight is not None:
            oprot.writeFieldBegin('serumHeight', TType.DOUBLE, 1)
            oprot.writeDouble(self.serumHeight)
            oprot.writeFieldEnd()
        if self.gelHeight is not None:
            oprot.writeFieldBegin('gelHeight', TType.DOUBLE, 2)
            oprot.writeDouble(self.gelHeight)
            oprot.writeFieldEnd()
        if self.cellsHeight is not None:
            oprot.writeFieldBegin('cellsHeight', TType.DOUBLE, 3)
            oprot.writeDouble(self.cellsHeight)
            oprot.writeFieldEnd()
        if self.allSampleHeight is not None:
            oprot.writeFieldBegin('allSampleHeight', TType.DOUBLE, 4)
            oprot.writeDouble(self.allSampleHeight)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class SampleVolume(object):
    """
    Attributes:
     - serumVolume
     - gelVolume
     - cellsVolume
     - allSampleVolume

    """
    thrift_spec = None


    def __init__(self, serumVolume = None, gelVolume = None, cellsVolume = None, allSampleVolume = None,):
        self.serumVolume = serumVolume
        self.gelVolume = gelVolume
        self.cellsVolume = cellsVolume
        self.allSampleVolume = allSampleVolume

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.DOUBLE:
                    self.serumVolume = iprot.readDouble()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.DOUBLE:
                    self.gelVolume = iprot.readDouble()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.DOUBLE:
                    self.cellsVolume = iprot.readDouble()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.DOUBLE:
                    self.allSampleVolume = iprot.readDouble()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('SampleVolume')
        if self.serumVolume is not None:
            oprot.writeFieldBegin('serumVolume', TType.DOUBLE, 1)
            oprot.writeDouble(self.serumVolume)
            oprot.writeFieldEnd()
        if self.gelVolume is not None:
            oprot.writeFieldBegin('gelVolume', TType.DOUBLE, 2)
            oprot.writeDouble(self.gelVolume)
            oprot.writeFieldEnd()
        if self.cellsVolume is not None:
            oprot.writeFieldBegin('cellsVolume', TType.DOUBLE, 3)
            oprot.writeDouble(self.cellsVolume)
            oprot.writeFieldEnd()
        if self.allSampleVolume is not None:
            oprot.writeFieldBegin('allSampleVolume', TType.DOUBLE, 4)
            oprot.writeDouble(self.allSampleVolume)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class SampleSizeInfo(object):
    """
    Attributes:
     - height
     - volume

    """
    thrift_spec = None


    def __init__(self, height = None, volume = None,):
        self.height = height
        self.volume = volume

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.height = SampleHeight()
                    self.height.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.STRUCT:
                    self.volume = SampleVolume()
                    self.volume.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('SampleSizeInfo')
        if self.height is not None:
            oprot.writeFieldBegin('height', TType.STRUCT, 1)
            self.height.write(oprot)
            oprot.writeFieldEnd()
        if self.volume is not None:
            oprot.writeFieldBegin('volume', TType.STRUCT, 2)
            self.volume.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class ImageInfo(object):
    """
    Attributes:
     - width
     - height
     - data

    """
    thrift_spec = None


    def __init__(self, width = None, height = None, data = None,):
        self.width = width
        self.height = height
        self.data = data

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I32:
                    self.width = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I32:
                    self.height = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.STRING:
                    self.data = iprot.readBinary()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('ImageInfo')
        if self.width is not None:
            oprot.writeFieldBegin('width', TType.I32, 1)
            oprot.writeI32(self.width)
            oprot.writeFieldEnd()
        if self.height is not None:
            oprot.writeFieldBegin('height', TType.I32, 2)
            oprot.writeI32(self.height)
            oprot.writeFieldEnd()
        if self.data is not None:
            oprot.writeFieldBegin('data', TType.STRING, 3)
            oprot.writeBinary(self.data)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class TubeRecgInfo(object):
    """
    Attributes:
     - barcode
     - tube
     - index
     - sample
     - centrifuged
     - liqImage
     - barImage
     - image

    """
    thrift_spec = None


    def __init__(self, barcode = None, tube = None, index = None, sample = None, centrifuged = None, liqImage = None, barImage = None, image = None,):
        self.barcode = barcode
        self.tube = tube
        self.index = index
        self.sample = sample
        self.centrifuged = centrifuged
        self.liqImage = liqImage
        self.barImage = barImage
        self.image = image

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRING:
                    self.barcode = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.STRUCT:
                    self.tube = TubeInfo()
                    self.tube.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.STRUCT:
                    self.index = SerumIndex()
                    self.index.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.STRUCT:
                    self.sample = SampleSizeInfo()
                    self.sample.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 5:
                if ftype == TType.BOOL:
                    self.centrifuged = iprot.readBool()
                else:
                    iprot.skip(ftype)
            elif fid == 6:
                if ftype == TType.STRUCT:
                    self.liqImage = ImageInfo()
                    self.liqImage.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 7:
                if ftype == TType.STRUCT:
                    self.barImage = ImageInfo()
                    self.barImage.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 8:
                if ftype == TType.LIST:
                    self.image = []
                    (_etype3, _size0) = iprot.readListBegin()
                    for _i4 in range(_size0):
                        _elem5 = ImageInfo()
                        _elem5.read(iprot)
                        self.image.append(_elem5)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('TubeRecgInfo')
        if self.barcode is not None:
            oprot.writeFieldBegin('barcode', TType.STRING, 1)
            oprot.writeString(self.barcode.encode('utf-8') if sys.version_info[0] == 2 else self.barcode)
            oprot.writeFieldEnd()
        if self.tube is not None:
            oprot.writeFieldBegin('tube', TType.STRUCT, 2)
            self.tube.write(oprot)
            oprot.writeFieldEnd()
        if self.index is not None:
            oprot.writeFieldBegin('index', TType.STRUCT, 3)
            self.index.write(oprot)
            oprot.writeFieldEnd()
        if self.sample is not None:
            oprot.writeFieldBegin('sample', TType.STRUCT, 4)
            self.sample.write(oprot)
            oprot.writeFieldEnd()
        if self.centrifuged is not None:
            oprot.writeFieldBegin('centrifuged', TType.BOOL, 5)
            oprot.writeBool(self.centrifuged)
            oprot.writeFieldEnd()
        if self.liqImage is not None:
            oprot.writeFieldBegin('liqImage', TType.STRUCT, 6)
            self.liqImage.write(oprot)
            oprot.writeFieldEnd()
        if self.barImage is not None:
            oprot.writeFieldBegin('barImage', TType.STRUCT, 7)
            self.barImage.write(oprot)
            oprot.writeFieldEnd()
        if self.image is not None:
            oprot.writeFieldBegin('image', TType.LIST, 8)
            oprot.writeListBegin(TType.STRUCT, len(self.image))
            for iter6 in self.image:
                iter6.write(oprot)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class TaskInfo(object):
    """
    Attributes:
     - taskId
     - gripperId
     - state
     - result
     - info

    """
    thrift_spec = None


    def __init__(self, taskId = None, gripperId = None, state = None, result = None, info = None,):
        self.taskId = taskId
        self.gripperId = gripperId
        self.state = state
        self.result = result
        self.info = info

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRING:
                    self.taskId = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I32:
                    self.gripperId = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.I32:
                    self.state = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.I32:
                    self.result = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 5:
                if ftype == TType.STRUCT:
                    self.info = TubeRecgInfo()
                    self.info.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('TaskInfo')
        if self.taskId is not None:
            oprot.writeFieldBegin('taskId', TType.STRING, 1)
            oprot.writeString(self.taskId.encode('utf-8') if sys.version_info[0] == 2 else self.taskId)
            oprot.writeFieldEnd()
        if self.gripperId is not None:
            oprot.writeFieldBegin('gripperId', TType.I32, 2)
            oprot.writeI32(self.gripperId)
            oprot.writeFieldEnd()
        if self.state is not None:
            oprot.writeFieldBegin('state', TType.I32, 3)
            oprot.writeI32(self.state)
            oprot.writeFieldEnd()
        if self.result is not None:
            oprot.writeFieldBegin('result', TType.I32, 4)
            oprot.writeI32(self.result)
            oprot.writeFieldEnd()
        if self.info is not None:
            oprot.writeFieldBegin('info', TType.STRUCT, 5)
            self.info.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class DeviceInfo(object):
    """
    Attributes:
     - runningState

    """
    thrift_spec = None


    def __init__(self, runningState = None,):
        self.runningState = runningState

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I32:
                    self.runningState = iprot.readI32()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('DeviceInfo')
        if self.runningState is not None:
            oprot.writeFieldBegin('runningState', TType.I32, 1)
            oprot.writeI32(self.runningState)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(TubeHatHSV)
TubeHatHSV.thrift_spec = (
    None,  # 0
    (1, TType.I32, 'H', None, None, ),  # 1
    (2, TType.I32, 'S', None, None, ),  # 2
    (3, TType.I32, 'V', None, None, ),  # 3
)
all_structs.append(TubeHatInfo)
TubeHatInfo.thrift_spec = (
    None,  # 0
    (1, TType.BOOL, 'hasHat', None, None, ),  # 1
    (2, TType.I32, 'color', None, None, ),  # 2
    (3, TType.STRUCT, 'hsv', [TubeHatHSV, None], None, ),  # 3
)
all_structs.append(TubeSpec)
TubeSpec.thrift_spec = (
    None,  # 0
    (1, TType.I32, 'width', None, None, ),  # 1
    (2, TType.I32, 'height', None, None, ),  # 2
    (3, TType.I32, 'top', None, None, ),  # 3
)
all_structs.append(TubeInfo)
TubeInfo.thrift_spec = (
    None,  # 0
    (1, TType.STRUCT, 'hatInfo', [TubeHatInfo, None], None, ),  # 1
    (2, TType.I32, 'type', None, None, ),  # 2
    (3, TType.STRUCT, 'spec', [TubeSpec, None], None, ),  # 3
)
all_structs.append(SerumIndex)
SerumIndex.thrift_spec = (
    None,  # 0
    (1, TType.I32, 'hemolysisLevel', None, None, ),  # 1
    (2, TType.I32, 'icterusLevel', None, None, ),  # 2
    (3, TType.I32, 'lipemiaLevel', None, None, ),  # 3
)
all_structs.append(SampleHeight)
SampleHeight.thrift_spec = (
    None,  # 0
    (1, TType.DOUBLE, 'serumHeight', None, None, ),  # 1
    (2, TType.DOUBLE, 'gelHeight', None, None, ),  # 2
    (3, TType.DOUBLE, 'cellsHeight', None, None, ),  # 3
    (4, TType.DOUBLE, 'allSampleHeight', None, None, ),  # 4
)
all_structs.append(SampleVolume)
SampleVolume.thrift_spec = (
    None,  # 0
    (1, TType.DOUBLE, 'serumVolume', None, None, ),  # 1
    (2, TType.DOUBLE, 'gelVolume', None, None, ),  # 2
    (3, TType.DOUBLE, 'cellsVolume', None, None, ),  # 3
    (4, TType.DOUBLE, 'allSampleVolume', None, None, ),  # 4
)
all_structs.append(SampleSizeInfo)
SampleSizeInfo.thrift_spec = (
    None,  # 0
    (1, TType.STRUCT, 'height', [SampleHeight, None], None, ),  # 1
    (2, TType.STRUCT, 'volume', [SampleVolume, None], None, ),  # 2
)
all_structs.append(ImageInfo)
ImageInfo.thrift_spec = (
    None,  # 0
    (1, TType.I32, 'width', None, None, ),  # 1
    (2, TType.I32, 'height', None, None, ),  # 2
    (3, TType.STRING, 'data', 'BINARY', None, ),  # 3
)
all_structs.append(TubeRecgInfo)
TubeRecgInfo.thrift_spec = (
    None,  # 0
    (1, TType.STRING, 'barcode', 'UTF8', None, ),  # 1
    (2, TType.STRUCT, 'tube', [TubeInfo, None], None, ),  # 2
    (3, TType.STRUCT, 'index', [SerumIndex, None], None, ),  # 3
    (4, TType.STRUCT, 'sample', [SampleSizeInfo, None], None, ),  # 4
    (5, TType.BOOL, 'centrifuged', None, None, ),  # 5
    (6, TType.STRUCT, 'liqImage', [ImageInfo, None], None, ),  # 6
    (7, TType.STRUCT, 'barImage', [ImageInfo, None], None, ),  # 7
    (8, TType.LIST, 'image', (TType.STRUCT, [ImageInfo, None], False), None, ),  # 8
)
all_structs.append(TaskInfo)
TaskInfo.thrift_spec = (
    None,  # 0
    (1, TType.STRING, 'taskId', 'UTF8', None, ),  # 1
    (2, TType.I32, 'gripperId', None, None, ),  # 2
    (3, TType.I32, 'state', None, None, ),  # 3
    (4, TType.I32, 'result', None, None, ),  # 4
    (5, TType.STRUCT, 'info', [TubeRecgInfo, None], None, ),  # 5
)
all_structs.append(DeviceInfo)
DeviceInfo.thrift_spec = (
    None,  # 0
    (1, TType.I32, 'runningState', None, None, ),  # 1
)
fix_spec(all_structs)
del all_structs
